### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by rakesh-reddy95** [STEM-Inv/STEM-Inv#1]
@lmm077  Thanks for the wonderful research. When can we expect the code release?

**Comment by XuejiFang** [comment]
same question

**Comment by lmm077** [comment]
Hello, thanks for your attention to STEM Inv. Ideally, we plan to open source the code in about one month. Please understand and be patient, thank you.

**Comment by lmm077** [comment]
Thanks for waiting. We have released the code based on Tokenflow and provided some examples.

**Comment by rakesh-reddy95** [comment]
Thank you.
